MemoryCellInputFile: sample_cells/sample_FeFET_cell.yaml

ProcessNode: 32
DeviceRoadmap: LOP

CacheAccessMode: Normal
Associativity: 8 # For cache only

OutputDirectory: 
OutputFilePrefix: sample_FeFET_32nm_result
EnablePruning: Yes

LocalWire:
  Type: LocalAggressive
  RepeaterType: RepeatedNone
  LowSwing: No

GlobalWire:
  Type: GlobalAggressive
  RepeaterType: RepeatedNone
  UseLowSwing: No

Routing: H-tree

InternalSensing: true

Temperature: 370 # Kelvin
RetentionTime: 40 # microseconds

BufferDesignOptimization: latency

