system: # same as 'sample_FeFET_32nm_sys_config.yaml'
  DesignTarget: cache
  Capacity:
    Value: 128
    Unit: KB
  WordWidth: 128 # bits
apps:
  run: existing
  profiler: perf
  patternconfig_path: configs/perf_run_config/memsyspatternconfig_hello.json
tech:
  run: existing
  array_characterization_result_path: configs/perf_run_config/sample_FeFET_32nm_result.yaml
